### ISSUE TITLE
T7 file error on Windows 10

### ISSUE THREAD

**Issue by Alextorres325** [bobbens/sketch_simplification#2]
I tried to run the simplify.py file, I've already installed all the dependencies needed, I downloaded Pytorch for Windows from here: https://github.com/peterjc123/pytorch-scripts

When I run the script, the next error about the T7 file appears: 

` Traceback (most recent call last):
  File "simplify.py", line 17, in <module>
    cache  = load_lua( opt.model )
  File "C:\Users\Lenovo\AppData\Local\Programs\Miniconda3\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 608, in load_lua
    return reader.read()
  File "C:\Users\Lenovo\AppData\Local\Programs\Miniconda3\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 595, in read
    return self.read_table()
  File "C:\Users\Lenovo\AppData\Local\Programs\Miniconda3\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 523, in wrapper
    result = fn(self, *args, **kwargs)
  File "C:\Users\Lenovo\AppData\Local\Programs\Miniconda3\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 572, in read_table
    v = self.read()
  File "C:\Users\Lenovo\AppData\Local\Programs\Miniconda3\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 593, in read
    return self.read_object()
  File "C:\Users\Lenovo\AppData\Local\Programs\Miniconda3\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 523, in wrapper
    result = fn(self, *args, **kwargs)
  File "C:\Users\Lenovo\AppData\Local\Programs\Miniconda3\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 546, in read_object
    return reader_registry[cls_name](self, version)
  File "C:\Users\Lenovo\AppData\Local\Programs\Miniconda3\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 243, in read_nn_class
    attributes = reader.read()
  File "C:\Users\Lenovo\AppData\Local\Programs\Miniconda3\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 595, in read
    return self.read_table()
  File "C:\Users\Lenovo\AppData\Local\Programs\Miniconda3\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 523, in wrapper
    result = fn(self, *args, **kwargs)
  File "C:\Users\Lenovo\AppData\Local\Programs\Miniconda3\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 571, in read_table
    k = self.read()
  File "C:\Users\Lenovo\AppData\Local\Programs\Miniconda3\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 595, in read
    return self.read_table()
  File "C:\Users\Lenovo\AppData\Local\Programs\Miniconda3\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 523, in wrapper
    result = fn(self, *args, **kwargs)
  File "C:\Users\Lenovo\AppData\Local\Programs\Miniconda3\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 572, in read_table
    v = self.read()
  File "C:\Users\Lenovo\AppData\Local\Programs\Miniconda3\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 593, in read
    return self.read_object()
  File "C:\Users\Lenovo\AppData\Local\Programs\Miniconda3\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 523, in wrapper
    result = fn(self, *args, **kwargs)
  File "C:\Users\Lenovo\AppData\Local\Programs\Miniconda3\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 546, in read_object
    return reader_registry[cls_name](self, version)
  File "C:\Users\Lenovo\AppData\Local\Programs\Miniconda3\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 318, in wrapper
    obj = build_fn(reader, version)
  File "C:\Users\Lenovo\AppData\Local\Programs\Miniconda3\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 318, in wrapper
    obj = build_fn(reader, version)
  File "C:\Users\Lenovo\AppData\Local\Programs\Miniconda3\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 243, in read_nn_class
    attributes = reader.read()
  File "C:\Users\Lenovo\AppData\Local\Programs\Miniconda3\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 595, in read
    return self.read_table()
  File "C:\Users\Lenovo\AppData\Local\Programs\Miniconda3\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 523, in wrapper
    result = fn(self, *args, **kwargs)
  File "C:\Users\Lenovo\AppData\Local\Programs\Miniconda3\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 571, in read_table
    k = self.read()
  File "C:\Users\Lenovo\AppData\Local\Programs\Miniconda3\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 598, in read
    "corrupted.".format(typeidx))
torch.utils.serialization.read_lua_file.T7ReaderException: unknown type id 1064941863. The file may be corrupted.`

I use Python 3.6 from Minianaconda 3

Any help is appreciated, thanks

**Comment by tiwawan** [comment]
I'm using Windows 10 and the same error was occurred. One solution is to run simplify.py via Bash on Ubuntu on Windows.

**Comment by lxfly2000** [comment]
Change `load_lua( opt.model )` to `load_lua( opt.model,long_size=8 )` when you run it on Windows.

**Comment by bobbens** [comment]
Try what other commenters say, but to be honest, I had no idea torch ran on non-linux, and as I do not use windows nor am familiar with it, I am unable to provide any feedback on the issue. I'll leave the issue open for visibility.

**Comment by dmitriy-kisil** [comment]
It help me, thanks) @lxfly2000

**Comment by noobgrow** [comment]
感谢！@lxfly2000

**Comment by lcxxxiii** [comment]
thanks！！@lxfly2000
